import React from 'react';
import './aboutFlowersStyle.css';
export const AboutFlowers = (props) => {
    return (
        <div id='AboutFlowers'>
            <div className='article'>
                <h2>Send Flowers Online in UAE via Ferns N Petals</h2>
                <p>One can always rely on flowers as thoughtful and affordable gifts for any festival or special occasion. Flowers bring freshness, positivity, and happiness to our lives, which makes them the perfect gift for every relationship. We at Ferns N Petals have some alluring flower bouquets and arrangements online created using roses, lilies, carnations, tulips, orchids, gerberas, and chrysanthemums. The magnificent flowers would soothe your mind and the joy of gifting the delicately designed floral gifts would be simply awesome. You will easily find Father’s Day, Women’s Day, Valentine’s Day, Birthdays, Anniversaries, Weddings, or Thank You flowers online here. These stunning floral gifts can be sent to your friends and relatives for every occasion. We assure you of hassle-free delivery service at the doorstep of your loved ones. The fresh and beautiful blossoms would also make meaningful housewarming gift ideas to extend congratulations to a loved one who has recently bought a new house. The vibrant blooms will bring love and cheer to their new abode and make their stay pleasant. So, send birthday flower bouquets to your loved ones and make their special day extra-special. You may use our midnight delivery service for this occasion. Among flowers, you will find the gorgeous rose, lily, tulip, anthurium, bird of paradise, gerbera daisy, and orchid flowers online. These charming flowers are available in bunches, bouquets, and box/vase/basket arrangements. They would enhance happiness and love in your life for sure. So, start exploring our beautiful collection of flowers and send them to your loved ones on various occasions. Another great news is that you can send flowers online anywhere in the UAE like Dubai, Sharjah, Fujairah, Abu Dhabi, etc.</p>

                <h2>Send Gorgeous Flowers in the UAE Online With Our Swift Delivery Services</h2>
                <p>Flowers are the wonderful gifts of nature that never fail to amaze people and put a smile on their face. The epitome of love, grace, and beauty, blooms make the perfect gift to surprise loved ones on any occasion. Ferns N Petals presents a wide variety of gorgeous floral gifts for every occasion and relationship. You can browse online our wonderful flower bouquets and arrangements designed with fresh roses, lilies, daisies, carnations, and chrysanthemum flowers. A mesmerizing bouquet of roses is the perfect choice to woo your lady love on Valentine’s Day. Or you can gift your wife forever rose in Dubai on the special occasion of wedding anniversary that will symbolize your eternal love for her and make her feel as if she is on cloud nine. Similarly, you can surprise your mom with an arrangement of carnations on Mother’s Day and thank her for everything she does to make your life beautiful. Once you have chosen flowers online, you can avail our hassle-free delivery services for flower delivery in Abu Dhabi and several other places in the UAE, such as Dubai, Fujairah, Ajman, etc. If you are ordering flowers at the last moment, then you can avail our same day gifts delivery service to ensure their timely delivery to the destination. You can also opt for our express, midnight, and next day delivery services to send flowers to your desired destination in the UAE. We have introduced our latest range of flower boxes in Dubai where fresh and attractive blooms are presented in appealing designer boxes. Your loved ones will be truly mesmerized on receiving such a lovely present that will show how much you care for them.</p>

                <h2>Send New Year Special Gifts in UAE Through Ferns N Petals</h2>
                <p>Ferns N Petals is the number one online gift store here in the UAE where you can always find the best gifts to greet your loved ones on any special occasion/festival. If you are excited about this upcoming New Year occasion, then, you can explore our website and find various New Year gifts for your friends and relatives. Roses, lilies, orchids, or tulips are found in the category of flowers in various bunches, bouquets, or vase/box/basket arrangements. Similarly, you can send New Year cakes to celebrate the arrival of 2020. We have cream cakes, fondant cakes, cheesecakes, cupcakes, designer cakes, etc. in flavors of vanilla, truffle, chocolate, blueberry, strawberry, butterscotch, pineapple, etc. You can also search for other gift ideas like plants, personalized products, chocolates, etc. Also, check our thoughtful New Year quotes and share them with your loved ones through WhatsApp or Messenger.</p>

                <h2>Buy Ravishing Flowers Online for Mother’s Day Celebration</h2>
                <p>Mother’s Day is one of the most important days of the year, which is celebrated on 12th May. On this special day, you can express affection and gratitude towards your mom for blessing you with a wonderful life and loving you selflessly. With our sweet and fragrant Mothers Day flowers you can show your mom that you care for her and will always do. Our cheerful arrangement of carnations, daisies, orchids, and lilies will put a big smile on her face and fill the entire house with happiness and positivity. So wait no more and order online pretty blooms to surprise your mom and make this day extra special for her. For this occasion, we have gathered some amazing messages written with love. These messages perfectly showcase the respect, admiration, appreciation, and gratitude for your mom. So, have a look at these awesome messages and send Mothers Day message to mom to make her feel special.</p>
            </div>
        </div>
    )
}